sudo: false
before-install:
- export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
env:
  global:
  - secure: RfK0aCfEXMS3VYJlwWCRvlC6uwMChf5c5CCF7C40RMT4e7PRMkeqgxTZnPXOoeunaC9/RenYkdNNqK5W8/5dt3JL/iQfJKQpHpnP56CdKbjVXYRXECdJWin7wXL3ZNe038kaD7cUlkMWC5XWe8TkYCJgTrsJ6etweMCL2UbLyM82cudqmwe92U44IltCpyYUxyQ6OCdJ8evpwwmWyfW9aszJxj9VUk1lH2L1F8wzMQk/PO7y+F73h2ryTcLeYeViJf2plY4NhnhETaJ4AgpMfOH2B1Yfj8lqS/vYOk6+LlfTZxuSNL1TSylykaJmOzh+f69UHHGETa517A6uBJuTTW39/up22SCw06Tf9eCzdevlrg5B2bqSKTiYLkgVPxN2yt/cUL8xzxt70IuALAjcdLxnEzmSGsOTJCx5/dvxwgZPlBP/0fpDIP9AgNOgQe7P3TVrAP+FJW+Nm+VUPHIPlmiw6Ji6ihxsYo6qVstGu1fh8SkvA4G4YDs2BO7cUrBiMadrjX/n8larn7kxlcu/o6ZcJZrLrfJBJsLjmQHiObBglm6dCMSJkAJEtASHQHYJ6ZlyAmQADw4DetZJ9Hdt9ueY7U7NDbRstcoqZVXWOUDVmeh+2TcXxhINE/sPQh6UW4U9BLlBYYFgXgL24TUo6E75y+8NHxBgEWNbGHwQnNQ=
  - secure: hY5f+p81oXwng19Pv0EWnytBAzknAVcWSPzm54zkJNE+L6BTAwyFokL4BkSL5D0pJXZn6z91XsPHpDMZDHga63TjT3jsMIdWAS12dmtOvbrBCf/suvuFHPRruG/ghn1dALU2ovlk1DdlWfH18EnFcVzIKNm6CoD055CI+e2m12sjt59ZATK4G7kgarbfPTnwqYmvRbErQxy6R0qwYLKvzkPDNizwELMGsMIY7ftQQT0H/7jhKIuDfO8ITjBRTVqks3JZlpvan7IhXz0RzmrTieNFWVOprvKWkOa2CRctCGiRq83X7Yfjxf53MBy0Gq95nQ5ByCnIztzFu5g8w4VyMKnBNaiCaXi6vnfcDMTpEt52VwAJebCH/y5lvkYXwwzMcdlArghN9byNGf5N8+Lvx/8i2qy53bqzeW70X2KPZp0575YX5VhRFWY7xxllkqVSUi4T/MJlsaoLLc6fsdkqsU9cOkw5dxIfeAJEeuG0AxwM33B3I7yHbUmWAt8n+Dz2IT86kdudeiNMIdPReosRs4f6StPo995oUpXwQrGayIBjeyt+2VMqRLGGwrxYVo2qO2DdusazGtMeWYPmXQl8rEu57gGiw9Nwiwqf1gYx1AZJjEgW8yHcFRAayaDiK6QwsiwZvFkF0UERlxpKv6KpZo/cYTRfOs6Mk8YWJO1UV/o=
language: node_js
node_js:
- 4
- 5
script:
- node_modules/.bin/shortcake test-ci
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: Mt7Lalak87WYiiJXvsQO1KLrRnSb4RCil1LBqaabedOnCiW/plkn1DYb57AKTU9AG2eZ7dLLxjmlmecfLwxo9BdtZ35K7Gvr/AiFwmXi7zWR/t/u71XPtG6Ush5awxIvNJV+blissFzEQT0lBUqdGbAuCetcTMbkK3IU3u11/0sXu3kdgdG6zyPuPVVBeqakqsa7D7h1Q6tQy3xT9mE931Z6Ux+LJQ/n0XjMgPX/yw2+jhp+0EtqD+VoYsqFohah5I9veiMfQPuhxvqMMKUgW/JhFkSWwf9fwpihsTUOL3/upB9wyeSEnXPl4MRz/lRALP+xUPPSIG5KRTFUmn0RvsozZev+e7xaTlBQ2BTzcF5BVZgBXySjUVG3BF5mk9KIaQmMpd0gXsH+8wgCSJfImwYYzapIGB0UzYjVN1JVytMbG+nJOKFQIIujGMpJMZpjpOjyAWAyRV3KmSXTpDU1uarCWsK8AaVJCBqbYfIVAcfs4yycNxIyTpiH+l8SfBuoPUuvZtAxvVSg5EP02CUr4HyTWeup9aCQml3MjAqb7l0RXqfeffTfh5m6Da+0Zces1V9FWuG6yJn8pRZgXMuNP0Oo57v3s/pxQ0c6jEU+7EiIJOCBiuv83dmJzfGRNa4kn18SkshyE6KEyMwyE536XAZFBJvQGcueQ1TyJDIzAM0=
addons:
  apt:
    packages:
    - xvfb
install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
- npm install
after_success:
- node_modules/.bin/shortcake coverage
